# Generated by Django 4.2.2 on 2023-06-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyApp', '0003_alter_usermodel_options_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='token',
            new_name='token_id',
        ),
    ]
